# -*- coding: utf-8 -*-
"""ExitExamG1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eROoqHGkbVJa_Qbv3oizDQhb9pywB-X8
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

"""**Task 1**"""

df = pd.read_csv("/content/G1.csv")
df

df.shape

df.info()

numerical_features = df.select_dtypes(include=['int64', 'float64']).columns.tolist()
categorical_features = df.select_dtypes(include=['object', 'category']).columns.tolist()

print("Numerical Features:", numerical_features)
print("Categorical Features:", categorical_features)

df.duplicated().sum()  #check for duplcates

df.isnull().sum() #check for missing values

df.isnull().mean()*100

df['Best_Shopping_Mode'].value_counts()

target = df['Best_Shopping_Mode']
print(target.value_counts())
print(target.value_counts(normalize=True) * 100)

target.value_counts().plot(kind='bar', color=['skyblue','salmon','lightgreen'])
plt.title("Shopping Mode Distribution")
plt.xlabel("Best Shopping Mode")
plt.ylabel("Count")
plt.show()

target.value_counts().plot(kind='pie', autopct='%1.1f%%', colors=['skyblue','salmon','lightgreen'])
plt.title("Shopping Mode Proportion")
plt.ylabel("")
plt.show()

"""Analytical Questions

1.   No, dataset is imbalanced.
2.   Online shopping Category is dominate half of the survey
3.   Online shopping is leading

**Task 2  **
"""

import seaborn as sns
import matplotlib.pyplot as plt

"""Numerical Features: ['Response_ID','Age', 'Review_Influence_Score', 'Social_Ads_Influence_Score', 'Price_Comparison_Frequency', 'Discount_Importance_Score', 'Likely_To_Buy_After_Ad_Score', 'Impulse_Purchase_Frequency', 'Online_Shopping_Satisfaction_Score', 'Trust_In_Online_Reviews_Score', 'Regret_After_Purchase_Frequency']"""

#histogram for Age
plt.figure(figsize=(6,4))
sns.histplot(df["Age"], bins=20, kde=True)
plt.title("Age Distribution")
plt.xlabel("Age")
plt.ylabel("Frequency")
plt.show()

#Review_Influence_Score
plt.figure(figsize=(6,4))
sns.histplot(df["Review_Influence_Score"], bins=20, kde=True)
plt.title("Review Influence Score Distribution")
plt.xlabel("Review Influence Score")
plt.show()

#Social_Ads_Influence_Score
plt.figure(figsize=(6,4))
sns.histplot(df["Social_Ads_Influence_Score"], bins=20, kde=True)
plt.title("Social Ads Influence Score Distribution")
plt.xlabel("Social Ads Influence Score")
plt.show()

#Price_Comparison_Frequency
plt.figure(figsize=(6,4))
sns.histplot(df["Price_Comparison_Frequency"], bins=20, kde=True)
plt.title("Price Comparison Frequency Distribution")
plt.xlabel("Price Comparison Frequency")
plt.show()

#Discount_Importance_Score
plt.figure(figsize=(6,4))
sns.histplot(df["Discount_Importance_Score"], bins=20, kde=True)
plt.title("Discount Importance Score Distribution")
plt.xlabel("Discount Importance Score")
plt.show()

#Likely_To_Buy_After_Ad_Score
plt.figure(figsize=(6,4))
sns.histplot(df["Likely_To_Buy_After_Ad_Score"], bins=20, kde=True)
plt.title("Likely To Buy After Ad Score Distribution")
plt.xlabel("Likely To Buy After Ad Score")
plt.show()

#Impulse_Purchase_Frequency
plt.figure(figsize=(6,4))
sns.histplot(df["Impulse_Purchase_Frequency"], bins=20, kde=True)
plt.title("Impulse Purchase Frequency Distribution")
plt.xlabel("Impulse Purchase Frequency")
plt.show()

#Online_Shopping_Satisfaction_Score
plt.figure(figsize=(6,4))
sns.histplot(df["Online_Shopping_Satisfaction_Score"], bins=20, kde=True)
plt.title("Online Shopping Satisfaction Score Distribution")
plt.xlabel("Online Shopping Satisfaction Score")
plt.show()

#Trust_In_Online_Reviews_Score
plt.figure(figsize=(6,4))
sns.histplot(df["Trust_In_Online_Reviews_Score"], bins=20, kde=True)
plt.title("Trust In Online Reviews Score Distribution")
plt.xlabel("Trust In Online Reviews Score")
plt.show()

#Regret_After_Purchase_Frequency
plt.figure(figsize=(6,4))
sns.histplot(df["Regret_After_Purchase_Frequency"], bins=20, kde=True)
plt.title("Regret After Purchase Frequency Distribution")
plt.xlabel("Regret After Purchase Frequency")
plt.show()

# Convert Age to numeric, non-numeric becomes NaN
df['Age'] = pd.to_numeric(df['Age'], errors='coerce')

# Check how many missing values
print(df['Age'].isna().sum())

# Fill missing ages with median (Age is skewed)
df['Age'] = df['Age'].fillna(df['Age'].median())

#numerical features with median
num_cols = df.select_dtypes(include=['int64','float64']).columns
df[num_cols] = df[num_cols].fillna(df[num_cols].median())

#categorical features with mode
cat_cols = df.select_dtypes(include=['object']).columns
for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

df.isnull().sum()

num_cols : ['Response_ID', 'Review_Influence_Score', 'Social_Ads_Influence_Score', 'Price_Comparison_Frequency', 'Discount_Importance_Score', 'Likely_To_Buy_After_Ad_Score', 'Impulse_Purchase_Frequency', 'Online_Shopping_Satisfaction_Score', 'Trust_In_Online_Reviews_Score', 'Regret_After_Purchase_Frequency']

for i in num_cols :
  plt.figure(figsize = (5,5))
  plt.boxplot(df[i])
  plt.title(i)   #boxplots for identifying outliers

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder

#Label Encoding for ordinal feature
label_enc = LabelEncoder()
df['Online_Shopping_Frequency'] = label_enc.fit_transform(df['Online_Shopping_Frequency'].astype(str))

label_enc = LabelEncoder()
df['Return_Frequency'] = label_enc.fit_transform(df['Return_Frequency'].astype(str))

print(df.columns.tolist())

#One-Hot Encoding for nominal feature
df = pd.get_dummies(df, columns=['Preferred_Payment_Method', 'Country_Region','Gender','Occupation_Status','Monthly_Income_Range',
    'Shop_Most_Where','Preferred_Platform','Primary_Device','Top_Spending_Category',
    'Follows_Brands_On_Social','Makes_Shopping_List','Avg_Monthly_Spend_NonEssentials',
    'Uses_BNPL_Installments',
    'Reason_Prefer_Online','Reason_Prefer_InStore'], drop_first=True)

from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE

# Convert Timestamp to datetime and extract features
df['Timestamp'] = pd.to_datetime(df['Timestamp'], errors='coerce')
df['Year'] = df['Timestamp'].dt.year
df['Month'] = df['Timestamp'].dt.month
df['DayOfWeek'] = df['Timestamp'].dt.dayofweek
df['Hour'] = df['Timestamp'].dt.hour

df.info()

bool_cols = df.select_dtypes(include=['bool']).columns.tolist()

# Convert True/False to 1/0
df[bool_cols] = df[bool_cols].astype(int)



target = 'Best_Shopping_Mode'

# Split features and target
X = df.drop(columns=[target])
y = df[target]

# Perform train-test split (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("Training set size:", X_train.shape)
print("Test set size:", X_test.shape)

bool_cols = df.select_dtypes(include=['bool']).columns
df[bool_cols] = df[bool_cols].astype(int)

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ['Gender','Occupation_Status','Country_Region', ...]  # your list
numerical_features = ['Age','Review_Influence_Score', ...]  # your list

preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features),
        ('num', StandardScaler(), numerical_features)
    ])

from sklearn.preprocessing import StandardScaler

# Example: define actual numeric columns
numerical_features = [
    'Age','Review_Influence_Score','Social_Ads_Influence_Score',
    'Price_Comparison_Frequency','Discount_Importance_Score',
    'Likely_To_Buy_After_Ad_Score','Impulse_Purchase_Frequency',
    'Return_Frequency','Online_Shopping_Satisfaction_Score',
    'Trust_In_Online_Reviews_Score','Regret_After_Purchase_Frequency'
]

# Select only numeric columns
X_train_num = X_train[numerical_features]

# Apply StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_num)
X_test_scaled = scaler.transform(X_test[numerical_features])

from imblearn.over_sampling import SMOTE

# Apply SMOTE on the scaled training set
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train_scaled, y_train)

print("Before SMOTE:\n", y_train.value_counts())
print("After SMOTE:\n", y_train_resampled.value_counts())

"""1.   Encoding, Scaling and SMOTE . Data is imbalanced , so used SMOTE to balance data
2.   Yes, it is affected , Median is used in numerical columns and mode is used in categorical columns

Task 3
"""

print(df.groupby('Best_Shopping_Mode')['Age'].describe())

import seaborn as sns
import matplotlib.pyplot as plt
#Age vs Shopping Mode
plt.figure(figsize=(8,6))
sns.boxplot(x='Best_Shopping_Mode', y='Age', data=df, palette='Set2')
plt.title("Age Distribution vs Shopping Mode")
plt.xlabel("Best Shopping Mode")
plt.ylabel("Age")
plt.show()

print(df.columns.tolist())

df.columns = df.columns.str.strip()

print(df.columns.tolist())

"""Income vs Spending"""

import seaborn as sns
import matplotlib.pyplot as plt
#Inome vs SPENDING
plt.figure(figsize=(8,6))
sns.boxplot(x='Monthly_Income_Range_Under $1,000', y='Avg_Monthly_Spend_NonEssentials_$500+', data=df, palette='Set2')
plt.title("Monthly Income vs Avg Monthly Spend Non-Essentials $500")
plt.xlabel("Monthly Income Range under 1000")
plt.ylabel("Avg Monthly Spend Non-Essentials")
plt.show()

"""Shopping Frequency"""

print(df['Online_Shopping_Frequency'].value_counts())
print(df['Online_Shopping_Frequency'].describe())

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8,6))
sns.countplot(x='Online_Shopping_Frequency', data=df, palette='Set2')
plt.title("Distribution of Online Shopping Frequency")
plt.xlabel("Shopping Frequency")
plt.ylabel("Count")
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(8,6))
sns.boxplot(x='Online_Shopping_Frequency', y='Age', data=df, palette='Set3')
plt.title("Age vs Shopping Frequency")
plt.xlabel("Shopping Frequency")
plt.ylabel("Age")
plt.xticks(rotation=45)
plt.show()

"""Satisfaction and Review Influence"""

print(df[['Online_Shopping_Satisfaction_Score','Review_Influence_Score']].corr())

print(df.groupby(pd.qcut(df['Review_Influence_Score'], 4))['Online_Shopping_Satisfaction_Score'].mean())

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8,6))
sns.scatterplot(x='Review_Influence_Score', y='Online_Shopping_Satisfaction_Score', data=df, alpha=0.6)
plt.title("Satisfaction vs Review Influence")
plt.xlabel("Review Influence Score")
plt.ylabel("Online Shopping Satisfaction Score")
plt.show()

df['Review_Quartile'] = pd.qcut(df['Review_Influence_Score'], 4, labels=['Low','Medium','High','Very High'])

plt.figure(figsize=(8,6))
sns.boxplot(x='Review_Quartile', y='Online_Shopping_Satisfaction_Score', data=df, palette='Set2')
plt.title("Satisfaction Distribution by Review Influence Quartile")
plt.xlabel("Review Influence Level")
plt.ylabel("Satisfaction Score")
plt.show()

"""Payment Method distribution"""

print(df.columns.tolist())

print(df['Preferred_Payment_Method_Credit Card'].value_counts())
print(df['Preferred_Payment_Method_Credit Card'].value_counts(normalize=True) * 100)

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8,6))
sns.countplot(x='Preferred_Payment_Method_Credit Card', data=df, palette='Set2')
plt.title("Distribution of Preferred Payment Methods Credit Card")
plt.xlabel("Payment Method")
plt.ylabel("Count")
plt.xticks(rotation=45)
plt.show()

print(df['Preferred_Payment_Method_Debit Card'].value_counts())
print(df['Preferred_Payment_Method_Debit Card'].value_counts(normalize=True) * 100)

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8,6))
sns.countplot(x='Preferred_Payment_Method_Debit Card', data=df, palette='Set2')
plt.title("Distribution of Preferred Payment Methods Debit Card")
plt.xlabel("Payment Method")
plt.ylabel("Count")
plt.xticks(rotation=45)
plt.show()

"""1,  Trust, convienient and place

2,  Yes

**Task 4**

Models - Classification Models
"""

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.metrics import classification_report

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

log_model = LogisticRegression(max_iter=1000)

log_model.fit(X_train_scaled, y_train)

y_pred_log = log_model.predict(X_test_scaled)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

print("Logistic Regression")
print("Accuracy:", accuracy_score(y_test, y_pred_log))
print("Precision:", precision_score(y_test, y_pred_log, average='macro'))
print("Recall:", recall_score(y_test, y_pred_log, average='macro'))
print("F1:", f1_score(y_test, y_pred_log, average='macro'))

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

rf_model = RandomForestClassifier(n_estimators=200, random_state=42)

rf_model.fit(X_train_scaled, y_train)

y_pred_rf = rf_model.predict(X_test_scaled)

print("Random Forest Results")
print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print("Precision:", precision_score(y_test, y_pred_rf, average='macro'))
print("Recall:", recall_score(y_test, y_pred_rf, average='macro'))
print("F1:", f1_score(y_test, y_pred_rf, average='macro'))
print("\nClassification Report:\n", classification_report(y_test, y_pred_rf))

from sklearn.ensemble import GradientBoostingClassifier

gb_model = GradientBoostingClassifier(random_state=42)

gb_model.fit(X_train_scaled, y_train)

y_pred_gb = gb_model.predict(X_test_scaled)

print("Gradient Boosting Results")
print("Accuracy:", accuracy_score(y_test, y_pred_gb))
print("Precision:", precision_score(y_test, y_pred_gb, average='macro'))
print("Recall:", recall_score(y_test, y_pred_gb, average='macro'))
print("F1:", f1_score(y_test, y_pred_gb, average='macro'))
print("\nClassification Report:\n", classification_report(y_test, y_pred_gb))

from sklearn.svm import SVC

svm_model = SVC()

svm_model.fit(X_train_scaled, y_train)

y_pred_svm = svm_model.predict(X_test_scaled)

print("Support Vector Machine Results")
print("Accuracy:", accuracy_score(y_test, y_pred_svm))
print("Precision:", precision_score(y_test, y_pred_svm, average='macro'))
print("Recall:", recall_score(y_test, y_pred_svm, average='macro'))
print("F1:", f1_score(y_test, y_pred_svm, average='macro'))
print("\nClassification Report:\n", classification_report(y_test, y_pred_svm))



results = {}
# Logistic Regression
results['Logistic Regression'] = {
    "Accuracy": accuracy_score(y_test, y_pred_log),
    "Precision": precision_score(y_test, y_pred_log, average='macro'),
    "Recall": recall_score(y_test, y_pred_log, average='macro'),
    "F1": f1_score(y_test, y_pred_log, average='macro')
}

# Random Forest
results['Random Forest'] = {
    "Accuracy": accuracy_score(y_test, y_pred_rf),
    "Precision": precision_score(y_test, y_pred_rf, average='macro'),
    "Recall": recall_score(y_test, y_pred_rf, average='macro'),
    "F1": f1_score(y_test, y_pred_rf, average='macro')
}

# Gradient Boosting
results['Gradient Boosting'] = {
    "Accuracy": accuracy_score(y_test, y_pred_gb),
    "Precision": precision_score(y_test, y_pred_gb, average='macro'),
    "Recall": recall_score(y_test, y_pred_gb, average='macro'),
    "F1": f1_score(y_test, y_pred_gb, average='macro')
}

# SVM
results['SVM'] = {
    "Accuracy": accuracy_score(y_test, y_pred_svm),
    "Precision": precision_score(y_test, y_pred_svm, average='macro'),
    "Recall": recall_score(y_test, y_pred_svm, average='macro'),
    "F1": f1_score(y_test, y_pred_svm, average='macro')
}

# Convert to DataFrame for easy comparison
df_results = pd.DataFrame(results).T
print(df_results)

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix

# Compute confusion matrix
cm = confusion_matrix(y_test, y_pred_svm)

# Plot heatmap
plt.figure(figsize=(8,6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=svm_model.classes_,
            yticklabels=svm_model.classes_)
plt.title("Confusion Matrix - SVM")
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.show()

#Most important features for predictions ,
Discount_Importance_Score

Online_Shopping_Satisfaction_Score

Trust_In_Online_Reviews_Score

Preferred_Payment_Method

Monthly_Income_Range

"""1,SVM model is performed well , because SVM don’t provide feature importance directly


2, Discount_Importance_Score , Online_Shopping_Satisfaction_Score, Trust_In_Online_Reviews_Score , Preferred_Payment_Method , Monthly_Income_Range

3,Larger absolute values indicate stronger influence on the decision boundary.




"""

import pandas as pd

# 1. Create comparison DataFrame for the first 100 test samples
comparison_df = pd.DataFrame({
    'Actual': y_test.values[:100],
    'Predicted': y_pred_svm[:100]
}).reset_index(drop=True)

# 2. Add a column to flag mismatches
comparison_df['Match?'] = comparison_df['Actual'] == comparison_df['Predicted']

# 3. Display the top 10 rows
print(comparison_df.head(10))

"""Task 5"""

1, Marketing ROI , Sales Growth , reduced returns
2,